version: '3'
services:
  mongo-shard01:
    container_name: mongo-shard01
    image: mongo
    command: mongod --shardsvr --replSet mongoshardrs01 --port 27017 --dbpath /data/db
    ports:
      - 20001:27017
    volumes:
      - mongo-shard01:/data/db
  mongo-shard02:
    container_name: mongo-shard02
    image: mongo
    command: mongod --shardsvr --replSet mongoshardrs02 --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - mongo-shard02:/data/db
  mongo-shard03:
    container_name: mongo-shard03
    image: mongo
    command: mongod --shardsvr --replSet mongoshardrs03 --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - mongo-shard03:/data/db
volumes:
  mongo-shard01: {}
  mongo-shard02: {}
  mongo-shard03: {}